/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import g8_ant.DB_Connection;
//Importar jdbc para crear conexion con base de datos mysql
import java.sql.*;

public class MainWindow extends javax.swing.JFrame {
    //variable de conexion a la base de datos
   
    public MainWindow() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        btn_ModifySuscriber = new javax.swing.JButton();
        btn_DeleteSuscriber = new javax.swing.JButton();
        btn_ListAreas = new javax.swing.JButton();
        btn_ShowWeakAreas = new javax.swing.JButton();
        btn_AddSuscriber = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Title.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        lbl_Title.setText("MANEJO DE REDES DE TELEVISIÓN POR CABLE");

        btn_ModifySuscriber.setText("Modificar suscriptor");
        btn_ModifySuscriber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModifySuscriberActionPerformed(evt);
            }
        });

        btn_DeleteSuscriber.setText("Eliminar suscriptor");
        btn_DeleteSuscriber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteSuscriberActionPerformed(evt);
            }
        });

        btn_ListAreas.setText("Listar sectores");
        btn_ListAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ListAreasMouseClicked(evt);
            }
        });
        btn_ListAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListAreasActionPerformed(evt);
            }
        });

        btn_ShowWeakAreas.setText("Mostrar sectores débiles");
        btn_ShowWeakAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowWeakAreasActionPerformed(evt);
            }
        });

        btn_AddSuscriber.setText("Agregar suscriptor");
        btn_AddSuscriber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddSuscriberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_DeleteSuscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ModifySuscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_AddSuscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ListAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_ShowWeakAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lbl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btn_ModifySuscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_DeleteSuscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ListAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_AddSuscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ShowWeakAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTONES: Asignacion de eventos asociados al presionarlos
    
    private void btn_ShowWeakAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowWeakAreasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_ShowWeakAreasActionPerformed

    private void btn_ModifySuscriberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModifySuscriberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ModifySuscriberActionPerformed

    private void btn_ListAreasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ListAreasMouseClicked
        
        ListSuscribersWindow listaSuscriptores = new ListSuscribersWindow();
        listaSuscriptores.init();
        //listaSuscriptores.init(connection);
    }//GEN-LAST:event_btn_ListAreasMouseClicked

    private void btn_AddSuscriberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddSuscriberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddSuscriberActionPerformed

    private void btn_DeleteSuscriberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteSuscriberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DeleteSuscriberActionPerformed

    private void btn_ListAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListAreasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_ListAreasActionPerformed

    //se inicializa con una referencia de la conexion a la BD
    public void init() {
        //se muestra
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddSuscriber;
    private javax.swing.JButton btn_DeleteSuscriber;
    private javax.swing.JButton btn_ListAreas;
    private javax.swing.JButton btn_ModifySuscriber;
    private javax.swing.JButton btn_ShowWeakAreas;
    private javax.swing.JLabel lbl_Title;
    // End of variables declaration//GEN-END:variables
}
